### ISSUE TITLE
Coalesce STIX ControlledVocabStringType w/ CybOX ControlledVocabStringType

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/schemas#297] opened 2015-04-01 20:43 UTC

**Comment by gtback** [comment] 2015-04-03 14:01
Duplicate of #141

**Comment by gtback** [comment] 2015-04-03 14:01
I'm especially impressed that both issues used the term "coalesce"

**Closed by gtback** 2015-04-03 14:01 UTC
Labels: Requires Community Feedback, Type-Enhancement

**Comment by johnwunder** [comment] 2015-04-03 14:03
Ha, we probably copied them both from the same place
