### ISSUE TITLE
Information Source field name discrepancies

### ISSUE THREAD

**Issue by jonathanbaker** [STIXProject/schemas#304] opened 2015-04-05 23:23 UTC
Reported by Brett Jordan:

On the RelatedIdentityType the field name is "Information_Source" 
http://stixproject.github.io/data-model/1.1.1/stixCommon/RelatedIdentityType/

And on the ConfidenceType the field is called "Source"
http://stixproject.github.io/data-model/1.1.1/stixCommon/ConfidenceType/

Can we standardize the field names?  I am guessing these are not the only two that are different.

**Comment by johnwunder** [comment] 2015-04-06 12:06
Duplicate of #263

**Closed by johnwunder** 2015-04-06 12:06 UTC
Labels: Com-Common, Res-Rejected
