### ISSUE TITLE
Indicator Kill Chains claims 0..1, however, it is plural

### ISSUE THREAD

**Issue by jordan2175** [STIXProject/schemas#288] opened 2015-03-10 22:15 UTC
http://stixproject.github.io/data-model/1.1.1/indicator/IndicatorType/

On this page we have Kill_Chain_Phases 0..1 -> Kill Chain Phase -> bla bla bla

Because Kill_Chain_Phases is plural, you would think that this would support an array of data so 0..n, however, the docs says it only supports a single entry 0..1.  If it only supports a single entry, then we should flatten it.  If it should support an array, then we need to change the docs.

**Comment by johnwunder** [comment] 2015-03-11 12:13
The reason `Kill_Chain_Phases` is a plural name is because it's a list container for a plural list of elements: `Kill_Chain_Phase`. I.e. in markup you get:

```xml
<Kill_Chain_Phases>
  <Kill_Chain_Phase />
  <Kill_Chain_Phase />
  <Kill_Chain_Phase />
</Kill_Chain_Phases>
```

This is how I recommended `IndicatorType/Type` work as well.

Given that this issue is effectively a duplicate of #262, which discusses how to represent list types, I recommend closing this one. @jordan2175 do you agree? If so go ahead and close.

**Comment by jordan2175** [comment] 2015-03-11 16:37
Well then if it should be a plural, then we need to change the docs on the page above to change the 0..1 to 0..n

**Comment by johnwunder** [comment] 2015-03-11 16:41
`<Kill_Chain_Phases>` is not plural, it's 0 to 1. `<Kill_Chain_Phase>` is plural.

Remember that the labels describe what's inside something...`Kill_Chain_Phases` contains multiple `Kill_Chain_Phase` elements so it uses a plural name even though it only occurs 0..1. `Kill_Chain_Phase` contains a single kill chain so is singular even though it occurs 0..n.

The alternative is to have something like this:

```xml
<Kill_Chain_Phase>
  <Kill_Chain_Phases>sdfsdf</Kill_Chain_Phases>
  <Kill_Chain_Phases>sdfsdf</Kill_Chain_Phases>
</Kill_Chain_Phase>
```

Which of course doesn't really make sense. Sorry if I'm not explaining this well but it is correct as-is.

**Comment by jordan2175** [comment] 2015-03-11 16:50
It just seems confusing...  As Alternate_ID is a 0..n, since it can take multiple string values.  (There is a different GitHub issue for make Alternate_ID plural).  And in your first comment to this issue you say:

```
<Kill_Chain_Phases>
  <Kill_Chain_Phase />
  <Kill_Chain_Phase />
  <Kill_Chain_Phase />
</Kill_Chain_Phases>
```
Which leads me to think that <Kill_Chain_Phases> can have multiple <Kill_Chain_Phase> lines in it.  As your example lists three of them.    So in my mind, it would be Kill_Chain_Phases 0..n not 0..1.  If it was 0..1 it would be something like:

```
<Kill_Chain_Phases>
  <Kill_Chain_Phase>
     data1,
     data2, 
     data3,
  </Kill_Chain_Phase>
</Kill_Chain_Phases>
```

**Comment by jordan2175** [comment] 2015-03-11 16:52
Updated on GitHub since it ate some of my markup

**Comment by johnwunder** [comment] 2015-03-11 17:05
Kill_Chain_Phases is 0..1, which means within an indicator you can either have zero Kill_Chain_Phases elements or 1 Kill_Chain_Phases element. I.e.

```xml
<Indicator>
  <Kill_Chain_Phases>
    <Kill_Chain_Phase>data 1</Kill_Chain_Phase>
    <Kill_Chain_Phase>data 2</Kill_Chain_Phase>
  </Kill_Chain_Phases>
</Indicator>
```

If we change it to 0..n, you could have between 0 and many cases, so:

```xml
<Indicator>
  <Kill_Chain_Phases>
    <Kill_Chain_Phase>data 1</Kill_Chain_Phase>
    <Kill_Chain_Phase>data 2</Kill_Chain_Phase>
  </Kill_Chain_Phases>
  <Kill_Chain_Phases>
    <Kill_Chain_Phase>data 3</Kill_Chain_Phase>
    <Kill_Chain_Phase>data 4</Kill_Chain_Phase>
  </Kill_Chain_Phases>
  <Kill_Chain_Phases>
    <Kill_Chain_Phase>data 5</Kill_Chain_Phase>
    <Kill_Chain_Phase>data 6</Kill_Chain_Phase>
  </Kill_Chain_Phases>
</Indicator>
```

As you can see the multiple `Kill_Chain_Phases` parents are not necessary...one is enough. That's why Kill_Chain_Phases is 0..n.

**Comment by sbarnum** [comment] 2015-03-11 17:05
Maybe this will help.

The plural name field is the "list". It is 0..1 because either there is a list present or not.
The singular name field is a "list item" in the list if the list is present. It is typically 1..n because the list can be of arbitrary length.

There are a couple of fields currently in STIX that do not follow this pattern of a "list" field enclosing a set of "list item" fields. They just have a list item field with 0..n.
The tracker issue John links to above is about addressing this inconsistency.

**Comment by jordan2175** [comment] 2015-03-11 18:43
I think I get it now...  Thanks for the extra explanation.  It might be good to figure out how best to document that so it is more clear.

**Closed** 2015-03-11 20:49 UTC
