### ISSUE TITLE
STIX Object IDs

### ISSUE THREAD

**Issue by brownsa** [STIXProject/schemas#352] opened 2015-08-05 20:15 UTC
I wanted to ask a question to the group that came up while testing interoperability between two STIX-enabled platforms.

The testing found a problem that arises as a result of System A not including object identifiers for nested objects, but System B being programmed to disregard anything without an object ID. Therefore, System B loses data from System A upon import.

While System B could relax this requirement, because STIX doesn’t require IDs on all objects (its not a requirement for valid STIX documents in the MITRE validator), we are wondering, if objects in STIX are supposed to be treated autonomously and not hierarchically, wouldn’t it be ideal if all objects did have corresponding IDs?  

Is this finding something worth considering?

**Comment by johnwunder** [comment] 2015-08-18 12:32
@brownsa, do you think this is covered by #221 and #336? #336 suggests removing IDs where they aren't useful (they show up in a surprising number of places) and #221 suggests making them required anytime they are used.

**Comment by sbarnum** [comment] 2015-11-13 16:53
This looks like it is a duplicate of #221

**Closed by sbarnum** 2015-11-13 16:53 UTC
Labels: Data-Model-centric, Simplification, Tier1
