### ISSUE TITLE
Unknown message type (Subscription_Management_Request)

### ISSUE THREAD

**Issue by AjayS91** [STIXProject/schemas#395] opened 2017-05-29 08:05 UTC
Below the code to subscribe to a feed on hailataxii.com

```
import libtaxii as t
import libtaxii.clients as tc
import libtaxii.messages_11 as tm11
from libtaxii.constants import *

client = tc.HttpClient()
client.set_auth_type(tc.HttpClient.AUTH_BASIC)
client.set_auth_credentials({'username': 'guest', 'password': 'guest'})

collecton_subscripton_request = tm11.ManageCollectionSubscriptionRequest(message_id=tm11.generate_message_id(),collection_name='guest.EmergineThreats_rules',action=ACT_SUBSCRIBE)
collecton_subscripton_xml = collecton_subscripton_request.to_xml()

http_resp = client.call_taxii_service2('hailataxii.com', '/taxii-data', VID_TAXII_XML_11, collecton_subscripton_xml)
taxii_message = t.get_message_from_http_response(http_resp, discovery_request.message_id)
print taxii_message.to_dict()

```
But I'm getting below error

`{'in_response_to': '2245850195147903371', 'status_detail': {}, 'extended_headers': {}, 'message': 'Unknown message type (Subscription_Management_Request)', 'message_type': 'Status_Message', 'message_id': '16855', 'status_type': 'FAILURE'}`

**Comment by gtback** [comment] 2017-05-31 16:54
Hi @AjayS91 !

It's not clear to me whether this is an issue with [libtaxii](https://github.com/TAXIIProject/libtaxii) or with hailataxii.com itself. I haven't used hailataxii.com, but I wouldn't be surprised if they don't support Subscription Requests. 

Either way, the issue is not related to the STIX schemas (this repository), so I'm going to close this issue, but feel free to open it on the libtaxii repo if you find there's something there that needs to be fixed.

**Closed** 2017-05-31 16:54 UTC

**Comment by AjayS91** [comment] 2017-06-01 07:33
Thanks @gtback .
 I have posted the same query on libtaxii repo.

**Comment by gtback** [comment] 2017-06-01 22:03
Thanks, @AjayS91 . I'll look into it more over there 😀
