### ISSUE TITLE
“Memory Error” while fetching feeds from hailataxii service?

### ISSUE THREAD

**Issue by Muhammad-Zaryaab-Shahbaz** [STIXProject/schemas#396] opened 2019-04-17 19:12 UTC
I am fetching feeds from **Hailataxii** service using Python's **libtaxii** library. It has 9 feeds, I have successfully fetched 6 feeds but 3 of the feeds are giving me **Memory Error**.

I have run this program on Linux with 15GB RAM, I tracked it for 6 hours and the memory utilization was exceeding and after 12 hours when I checked the progress again, it was displaying **Memory Error**.

```
import libtaxii as t
import libtaxii.messages_11 as tm11
import libtaxii.clients as tc
from libtaxii.common import generate_message_id
from libtaxii.constants import *

RESULTING_FOLDER = 'results'

FEEDS = [
    'Abuse_ch',
    'CyberCrime_Tracker',
    'EmergingThreats_rules',
    'Lehigh_edu',
    'MalwareDomainList_Hostlist',
    'blutmagie_de_torExits',
    'dataForLast_7daysOnly',
    'dshield_BlockList',
    'phishtank_com'
]

USERNAME = 'guest'

PASSWORD = 'guest'


def main(username, password, feeds, result_folder):
    client = tc.HttpClient()
    client.set_auth_type(tc.HttpClient.AUTH_BASIC)
    client.set_auth_credentials({'username': username, 'password': password})
    client.set_use_https(False)

    for feed in feeds:
        print('Start extracting `{}` feed ({}/{})'.format(feed, feeds.index(feed)+1, len(feeds)))
        #print('Start extracting `'+str(feed)+'` feed ('+str(feeds.index(feed)+1)+'/'+str(len(feeds))+')')
        poll_request = tm11.PollRequest(generate_message_id(),
                                        collection_name=feed,
                                        subscription_id=generate_message_id())
        poll_xml = poll_request.to_xml(pretty_print=True)
        http_resp = client.call_taxii_service2('hailataxii.com', '/taxii-data', VID_TAXII_XML_11, poll_xml)
        taxii_message = t.get_message_from_http_response(http_resp, poll_request.message_id)
```

I expected creation of an XML file in results directory because the code after **get_message_from_http_response()** function writes the response in an XML format. All feeds were extracted successfully except blutmagie_de_torExits, dataForLast_7daysOnly and phishtank_com.
Error in console is
```
Traceback (most recent call last): 
 File "hailataxii_feeds_saver.py", line 63, in <module> 
    feeds.feeds_arg, result_folder.result_folder_arg) 
 File "hailataxii_feeds_saver.py", line 31, in main 
    http_resp, poll_request.message_id) 
 File "/home/bscs8/.local/lib/python2.7/site-packages/libtaxii/ init .py", li ne 47, in get_message_from_http_response 
    return get_message_from_urllib_addinfourl(http_response, in_response_to) 
 File "/home/bscs8/.local/lib/python2.7/site-packages/libtaxii/ init .py", li ne 109, in get_message_from_urllib_addinfourl 
    return tmll.get_message_from_xml(response_message, encoding) 
 File "/home/bscs8/.local/lib/python2.7/site-packages/libtaxii/messages_11.py", line 75, in get_message_from_xml 
    xml_string = xml_string.decode(encoding, 'replace') 
 File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode 
    return codecs.utf_8_decode(input, errors, True) 
MemoryError 
```

**Comment by emmanvg** [comment] 2019-04-18 12:46
Closing as unrelated to this repo. Duplicate of https://github.com/TAXIIProject/libtaxii/issues/236

**Closed as completed by emmanvg** 2019-04-18 12:46 UTC
